providers = ["node"]

[phases.setup]
nixPkgs = [
  'nodejs_20',
  'python311',
  'pkg-config',
  'vips',
  'gcc'
]

[phases.install]
cmds = [
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd server && npm run build",
  "cd client && npm install --legacy-peer-deps",
  "cd client && npm run build",
  "rm -rf server/client/build",
  "cp -r client/build server/client/"
]

[environment]
SHARP_IGNORE_GLOBAL_LIBVIPS = "0"

[start]
cmd = "cd server && npm start"

